### ISSUE TITLE
Webpack relative import issue

### ISSUE THREAD

**Issue by thejohnhoffer** [thejohnhoffer/use-hash-history#28]
After Version 1.2 split the source code into three files, there is now an ES6 import issue with Webpack. It's [solvable](https://github.com/webpack/webpack/issues/11467#issuecomment-808618999) with `fullySpecified: false` in the Webpack configuration file. In a Webpack 5 project's webpack.config.js, the necessary ES6 JS "rule" should be:

```js
rules: [
  {
    test: /\.m?js/,
    resolve: {
        fullySpecified: false
    }
  }
]
```

In the long term, I may updating this package's build process to either:
- include `.js` extensions in compiled relative import statements.
- bundle the entire project into one file, avoiding relative imports.

**Comment by thejohnhoffer** [comment]
Fixed in [latest release](https://github.com/thejohnhoffer/use-hash-history/releases/tag/v1.3.4).

**Comment by palashkaria** [comment]
Hey, thank you so much for making this. I am porting over a large project & it wouldn't be possible without this!

I'm on `use-hash-history@^1.3.4` on `webpack@^5.64.4` (via `react-scripts@^5.0.1`), but I still needed this fix, as it still was without extensions in the final build (`./transcoder`). I know it's been a while since you made this, but you would want to check that out. 

Thanks for providing this workaround though! I will move the application to vite at some point so for now this works!
